apiVersion: v1
kind: ServiceAccount
metadata:
  name: gardener-admin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gardener-admin
subjects:
- kind: ServiceAccount
  name: gardener-admin
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

